version: '3'
services:
  postgres:
    build:
      context: ./postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  zookeeper:
    image: debezium/zookeeper:1.2
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:1.2
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    links:
      - zookeeper
  connect:
    image: debezium/connect:1.2
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    links:
      - postgres
      - kafka
  elastic:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  users:
    image: realtime-search/users:0.1.0
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    links:
      - postgres
  indexer:
    image: realtime-search/indexer:0.1.0
    ports:
      - 8082:8082
    environment:
      - KAFKA_SERVERS=kafka:9092
      - ELASTICSEARCH_SERVERS=elastic:9200
    links:
      - kafka
  search:
    image: realtime-search/search:0.1.0
    ports:
      - 8081:8081
    environment:
      - ELASTICSEARCH_SERVERS=elastic:9200
      - USERS_BASE_URL=users:8080/api
    links:
      - elastic
      - users
